<template>
    <div>
        <h1 class="text-center">Tipos de Contrato</h1>
        <h2> "Contrato por tempo indeterminado" </h2> <p>, 'Nesse modelo, não há um prazo final para as atividades. Fica a critério da empresa e colaborador dar fim ao contrato, sendo necessário um aviso prévio em caso de rescisão, Com a reforma trabalhista vigente, poderá ser feito um acordo entre empresa e trabalhador, para finalizar o contrato. Tendo sido tomada essa decisão, o empregador deve pagar ao funcionário a metade do aviso prévio e a metade da multa dos 40% sobre o saldo do FGTS' </p>
        <br /><h2> 'Contrato por tempo determinado '</h2><p>,  'Diferentemente da opção anterior, nesse tipo de contrato de trabalho o empregador deve estabelecer a data de início e final de sua vigência, que não deve ultrapassar o período de dois anos. Caso ele seja prorrogado mais de uma vez, ultrapassando esse limite, então deverá ser alterado e passar a constar como contrato indeterminado. A validade desse contrato é baseada em três hipóteses, segundo o que diz a  Consolidação das Leis do Trabalho (CLT). São elas: 1- contratação de serviço cuja natureza justifique a predeterminação do prazo do contrato; 2- contratação de atividades empresariais de caráter transitório; 3- contratação de colaborador em caráter de experiência.Ao final do contrato o trabalhador tem direitos reduzidos. Ele não tem garantia de aviso prévio, assim como acesso à multa de 40% do FGTS ou seguro desemprego.'</p>
        <br /><h2> 'Contrato de trabalho temporário'</h2><p>,  'O contrato de trabalho temporário também consta com uma data de início e fim. Porém, ele é voltado para o desenvolvimento de atividades por um período mais reduzido. O tempo máximo permitido para a vigência do contrato atualmente é de 120 dias, sendo consecutivos ou não. Além disso, esse prazo pode ser estendido uma única vez, pelo mesmo período. Nessa modalidade, a empresa também deve registrar as condições na carteira de trabalho do profissional, que terá os mesmos direitos do regime de prazo indeterminado, como previstos na CLT.' </p>
        <br /><h2> 'Contrato de trabalho autônomo'</h2><p>,  'As empresas podem contratar pessoas para prestação de serviços regulares mas não necessariamente contínuos, mediante o pagamento de salário previamente combinado. A reforma trabalhista também aponta que esse profissional não tem vínculo com a empresa contratante e sua carteira não é assinada. Da mesma forma, não há subordinação jurídica e o contrato não pode exigir exclusividade. Essa categoria de profissional se enquadra em pessoa física, por isso seu pagamento se dá através da emissão de um Recibo de Pagamento a Autônomo (RPA). Neste recibo o empregador deve destacar as contribuições previdenciárias (INSS) referente a prestação de serviço, imposto de renda (IRRF) e o ISS retido, dependendo da atividade exercida e município do profissional. Além disso, ele não tem acesso aos direitos trabalhistas previstos pela CLT, mas pode contribuir de forma individual com o INSS, tendo acesso aos benefícios básicos como auxílio-doença e salário-maternidade, por exemplo.' </p>
        <br /><h2> 'Contrato de prestação de serviços'</h2><p>,  'Essa modalidade se assemelha ao contrato de autônomo, a diferença é que o profissional em questão é classificado como pessoa jurídica, ou seja, apresenta CNPJ. Regulamentado como Microempreendedor Individual (MEI), o pagamento desse profissional  se dá por meio da emissão de nota fiscal. A contribuição ao governo, nesse caso, fica por conta do prestador de serviços, sendo realizada através Simples Nacional, sistema que também garante acesso a benefícios básicos do INSS.' </p>
        <br /><h2> 'Contrato de trabalho terceirizado'</h2><p>,  'Esse tipo de contrato é firmado entre duas empresas, quando alguma atividade da empresa contratante (seja ela uma atividade-meio ou atividade-fim) é repassada à responsabilidade de uma contratada especializada em determinada área.. A contratada fica responsável pelo vínculo com os funcionários, realizando pagamentos, treinamentos e demais obrigações. O contrato de trabalho terceirizado não tem prazo determinado.' </p>
        <br /><h2> 'Contrato de trabalho intermitente'</h2><p>,  'Esse é outro modelo entre tipos de contrato de trabalho que permitem que um profissional atue sob uma jornada de trabalho esporádica e que a sua remuneração seja de acordo com período da prestação de serviços. As regras aqui são de que a quantia não pode ser inferior à hora de trabalho de um funcionário que exerça a mesma função, sendo ele intermitente ou não. Outro ponto que o diferencia do contrato de prestação de serviços, por exemplo, é que nesse regime o colaborador tem o direito a férias, FGTS, previdência e 13º salário proporcionais. O contrato intermitente também não pode exigir exclusividade em períodos de inatividade.' </p>
        <br /><h2> 'Contrato de trabalho parcial'</h2><p>,  'O contrato de trabalho parcial conta com jornada de trabalho reduzida, tendo um limite de 30 horas semanais, sem a possibilidade de realização de horas extras, ou uma jornada de até 26 horas semanais, com a possibilidade de seis horas extras semanais. As férias também são de trinta dias por ano e os contratados nesse regime podem optar por receber um terço desse período em forma de pagamento.' </p>
        <br /><h2> 'Contrato de trabalho home office'</h2><p>,  'Esse também é um dos tipos de contrato de trabalho regulamentados pela reforma trabalhista. O home office é destinado ao profissional que vai atuar prioritariamente fora das dependências da empresa, podendo comparecer nela esporadicamente. As atividades desempenhadas por esses colaboradores, bem como os equipamentos para sua realização, devem constar no documento do acordo.' </p>
        <br /><h2> 'Contrato de trabalho de estágio'</h2><p>,  'O contrato de estágio é destinado a estudantes que buscam aprimorar alguma habilidade profissional antes de se formarem em determinada área. A carga horária não pode ultrapassar mais do que 30 horas semanais e, em de um período de prestação de serviço acima de um ano, o aluno tem direito aos 30 dias de férias.' </p>
        <br /><h2> 'Contrato de trabalho Verde e Amarelo'</h2><p>,  'O contrato Verde e Amarelo também tem um prazo determinado de dois anos, porém, visa exclusivamente jovens de até 29 anos, com uma condição de que seja o primeiro emprego formal do trabalhador. ' </p>
    </div>

</template>